name: Build macOS App and Zip

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-mac-app:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install py2app pandas openpyxl

      - name: Build .app using py2app
        run: |
          python3 setup.py py2app

      - name: Zip the .app
        run: |
          cd dist
          zip -r 발주자동기입기.zip 발주자동기입기.app

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v3
        with:
          name: 발주자동기입기_mac
          path: dist/발주자동기입기.zip
