name: Build macOS App and Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install py2app pandas openpyxl

      - name: Build app
        run: python3 setup.py py2app

      - name: Zip the app
        run: |
          cd dist
          zip -r 쭌파일변환기.zip 쭌파일변환기.app

      - name: Create GitHub Release and Upload
        uses: softprops/action-gh-release@v1
        with:
          name: 쭌파일변환기 자동 릴리스
          tag_name: v1.0.${{ github.run_number }}
          files: dist/쭌파일변환기.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
